### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by aheusingfeld** [aim42/aim42.org-site#15]
As discussed here is a number of ideas I have on aim42.org:

1. landingpage heading should be "Architecture Improvement Method"

done.

2. "Method Guide" should be the first item in the top level navigation, replacing "Overview"

It's now "Reference Manual"

3. Let's place the overview a.k.a. the "Elevator Pitch" on the landing page, replacing the "in short" section

yep, mostly done.

4. "detailed-intro" page should directly contain texts of the currently separate Analyze, Evaluate, Improve and Fundamentals pages, and make the latter stress the importance of separating the cross-cutting IssueList and ImprovementBacklog

5. Think about removing the "Background" page or replacing it with "Intention" or "History"

new issued #21 

6. Naming of the Method Guide should be consistent, sometimes we have "Reference Manual", sometimes "Reference Guide"

see new issue #20

7. Rename "Docs" to "Getting Started", it's a well-known trigger for visitors

done.

8. Double check that the links to the homepage (link behind the aim42 logo) works on all the subpages

link is generated by Jekyll, should work in all situations...

**Comment by gernotstarke** [comment]
I completely overhauled the navigation - so several of your comments are "fixed".
