### ISSUE TITLE
fix "Examples"

### ISSUE THREAD

**Issue by gernotstarke** [aim42/aim42.org-site#6]
provide (real-world) examples where we (or anybody somewhat credible) has applied aim42 patterns to practical systems/organizations.

That could be (strictly anonymized) customer situations, or
even real organizations describing their own effort/success/issues with aim42.

Maybe the term "Experience" is better suited to describe the intention.

Such experiences might range from
* just analyses, e.g. architecture or system reviews
* just improvements, based upon arbitrary prior work 
* any combination of (aim42-)practices

**Comment by aheusingfeld** [comment]
could you maybe be a bit elaborate on what the issue and intention is? :)

**Comment by gernotstarke** [comment]
done with new navigation
